### ISSUE TITLE
Joining data

### ISSUE THREAD

**Issue by leolorenzoluis** [the-gamma/thegamma#3]
Hey Tomas,

I'm currently working on a project where the gamma service might fit my use case. Is it possible to join different data sources that are provided from a rest service with a common key?

**Comment by tpetricek** [comment]
Hi! I guess I should check the issues here more often :)

Joining data is something I'm currently looking into - having a use case for that from you would be super useful for getting this right. Can you share more details (if it is still relevant)?

**Comment by leolorenzoluis** [comment]
Thank you. Apologize for the late response. I'd love to share my use case. The idea is that we have analysts that will have to query from different data source mostly for data/ad hoc analysis. They are mostly used in R or Python, but would love them to introduce to the power of F# and at the same time to be able to have intellisense while exploring the datasets that they are combining. Would love to talk more in private for now, should I contact you at slack? :)

**Comment by tpetricek** [comment]
@leolorenzoluis yes, feel free to ping me on Slack. But to avoid misunderstandings - The Gamma does not give you F# running in a browser. It has a much simpler minimal language with its own parser and type checker. It pretty much only lets you access data and do basic aggregations like the ones in the gallery (https://gallery.thegamma.net), which any experienced R or Python person can do in R or Python.

There are certainly ways of running F# in a browser too, but building that would be a lot more work. If your company was interested in this then let me know - and either me or my colleagues at @fsharpworks can discuss how to help with that!
